### PR TITLE
Add antithesis

### PR DESCRIPTION
**Pull request by adfaure**
Sources:
- https://discourse.nixos.org/t/nix-developer-role-antithesis-startup-on-site-in-dc-area/18234
- https://antithesis.breezy.hr/p/4eece462b5eb-senior-software-engineer

### CODE REVIEW

**Comment by ad-si** [comment]
@adfaure Why did you close it again?

**Comment by adfaure** [comment]
I wanted to create a merge request to your repository, not to my fork.

**Comment by ad-si** [comment]
But everything was fine as far as I can tell. Just reopen it and I will merge it!

**Comment by adfaure** [comment]
It is already merged to your repository (https://github.com/ad-si/nix-companies/commit/a7a4afaaa1dd54e03dd89fa00775474da054075e), so we are all good I guess :)

**Comment by ad-si** [comment]
Oh wow, I thought I was in my repo but this is yours. Weird. 😳
I even got a notification about it. Just another thing to look out for I guess … 😅

Anyways, thanks again for your help! =)

**Pull request closed without merging**
